server:
  port: ${SERVER_PORT}
spring:
  application:
    name: "noted"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"

  jpa:
    hibernate:
      ddl-auto: "update"

    properties:
      hibernate:
        dialect: "org.hibernate.dialect.PostgreSQLDialect"

  h2:
    datasource:
      url: ${SESSION_DB_URL}
      username: ${SESSION_DB_USERNAME}
      password: ${SESSION_DB_PASSWORD}
      driver-class-name: "org.h2.Driver"
      schema: "classpath:org/springframework/session/jdbc/schema-h2.sql"
    console:
      enabled: true
      path: "/h2-console"

  session:
    store-type: "jdbc"
    jdbc:
      initialize-schema: "always"
      table-name: "SPRING_SESSION"

hibernate:
  default_fetch_mode: "select"

logging:
  level:
    org:
      springframework:
        security: DEBUG

